activate_dataset: fmri
data_root: &d_r data
citation_root: data
add_self_loop: True
model: DHGNN_v1
k_nearest: 4
k_cluster: 4
adjacent_centers: 1
n_layers: 2
layer_spec: [90]
has_bias: True
wu_knn: 0
wu_kmeans: 10
wu_struct: 5
max_epoch: 250
milestones: [200]
gamma: 0.5
lr: 0.001
drop_out: 0.5
print_freq: 1
weight_decay: 0.0005
test_time: 5
